# Generated by Django 4.2 on 2026-09-25 23:50

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[apps.core.validators.validate_adult], verbose_name='data de nascimento'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não dizer')], default='', max_length=4, verbose_name='género'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_document_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='número do documento'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_document_type',
            field=models.CharField(blank=True, choices=[('BI', 'Bilhete de identidade'), ('PASSPORT', 'Passaporte')], default='', max_length=12, verbose_name='tipo de documento'),
        ),
        migrations.AddField(
            model_name='user',
            name='nif',
            field=models.CharField(blank=True, help_text='9 dígitos, 2 letras e 3 dígitos. Ex.: 009671373HA093', max_length=14, null=True, unique=True, validators=[apps.core.validators.validate_nif], verbose_name='NIF'),
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, choices=[('BENGO', 'Bengo'), ('BENGUELA', 'Benguela'), ('BIE', 'Bié'), ('CABINDA', 'Cabinda'), ('CUANDO_CUBANGO', 'Cuando Cubango'), ('CUANZA_NORTE', 'Cuanza Norte'), ('CUANZA_SUL', 'Cuanza Sul'), ('CUNENE', 'Cunene'), ('HUAMBO', 'Huambo'), ('HUILA', 'Huíla'), ('LUANDA', 'Luanda'), ('LUNDA_NORTE', 'Lunda Norte'), ('LUNDA_SUL', 'Lunda Sul'), ('MALANJE', 'Malanje'), ('MOXICO', 'Moxico'), ('NAMIBE', 'Namibe'), ('UIGE', 'Uíge'), ('ZAIRE', 'Zaire')], default='', max_length=20, verbose_name='província de residência'),
        ),
    ]
