# Generated by Django 4.2 on 2026-09-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/%Y/%m/', verbose_name='fotografia de perfil'),
        ),
    ]
