# Generated by Django 4.2.30 on 2026-09-27 21:35

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=apps.core.storage.storage_perfis, upload_to='perfis/%Y/%m/', verbose_name='fotografia de perfil'),
        ),
    ]
