# Generated by Django 4.2.30 on 2026-09-28 19:45

"""Desempata a lista de contas pelo `id`.

`full_name` é a ordenação de um directório de pessoas, e o directório é
paginado. O nome é uma chave fraca em Angola — «Ana Silva» há mais de uma pessoa
— e sem o `id` a mesma conta podia aparecer em duas páginas e outra em nenhuma.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['full_name', 'id'], 'verbose_name': 'utilizador', 'verbose_name_plural': 'utilizadores'},
        ),
    ]
