# Generated by Django 4.2 on 2026-09-25 21:48

import apps.core.validators
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='nome completo')),
                ('phone', models.CharField(max_length=20, validators=[apps.core.validators.validate_angolan_phone], verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('whatsapp', models.CharField(blank=True, max_length=20, validators=[apps.core.validators.validate_angolan_phone], verbose_name='WhatsApp')),
                ('id_document_type', models.CharField(choices=[('BI', 'Bilhete de identidade'), ('PASSPORT', 'Passaporte')], max_length=20, verbose_name='tipo de documento')),
                ('id_document_number', models.CharField(max_length=40, verbose_name='número do documento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owners_registered', to=settings.AUTH_USER_MODEL, verbose_name='registado por')),
            ],
            options={
                'verbose_name': 'proprietário',
                'verbose_name_plural': 'proprietários',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Código interno legível, por exemplo ECH-LU-0142.', max_length=20, unique=True, verbose_name='referência')),
                ('title', models.CharField(max_length=140, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('type', models.CharField(choices=[('HOUSE', 'Casa'), ('APARTMENT', 'Apartamento'), ('LAND', 'Terreno'), ('OFFICE', 'Escritório'), ('SHOP', 'Loja'), ('WAREHOUSE', 'Armazém')], max_length=12, verbose_name='tipologia')),
                ('purpose', models.CharField(choices=[('RENT', 'Arrendar'), ('SALE', 'Vender')], max_length=6, verbose_name='finalidade')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('IN_REVIEW', 'Em revisão'), ('UNDER_VALIDATION', 'Em validação'), ('CHANGES_REQUESTED', 'Pedido de alterações'), ('PUBLISHED', 'Publicado'), ('ARCHIVED', 'Arquivado'), ('REJECTED', 'Recusado')], db_index=True, default='DRAFT', max_length=20, verbose_name='estado')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='preço')),
                ('currency', models.CharField(default='AOA', max_length=3, verbose_name='moeda')),
                ('lease_term_months', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='prazo do contrato (meses)')),
                ('accepts_annual_payment', models.BooleanField(default=False, verbose_name='aceita pagamento anual')),
                ('province_ref', models.CharField(choices=[('BENGO', 'Bengo'), ('BENGUELA', 'Benguela'), ('BIE', 'Bié'), ('CABINDA', 'Cabinda'), ('CUANDO_CUBANGO', 'Cuando Cubango'), ('CUANZA_NORTE', 'Cuanza Norte'), ('CUANZA_SUL', 'Cuanza Sul'), ('CUNENE', 'Cunene'), ('HUAMBO', 'Huambo'), ('HUILA', 'Huíla'), ('LUANDA', 'Luanda'), ('LUNDA_NORTE', 'Lunda Norte'), ('LUNDA_SUL', 'Lunda Sul'), ('MALANJE', 'Malanje'), ('MOXICO', 'Moxico'), ('NAMIBE', 'Namibe'), ('UIGE', 'Uíge'), ('ZAIRE', 'Zaire')], db_index=True, max_length=20, verbose_name='província')),
                ('municipality', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='município')),
                ('locality', models.CharField(blank=True, max_length=120, verbose_name='localidade')),
                ('address_hint', models.CharField(blank=True, help_text='Nunca publicado. Divulgado apenas após agendamento de visita.', max_length=240, verbose_name='indício de morada')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MaxValueValidator(Decimal('18.0')), django.core.validators.MinValueValidator(Decimal('-18.0'))], verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MaxValueValidator(Decimal('36.0')), django.core.validators.MinValueValidator(Decimal('-36.0'))], verbose_name='longitude')),
                ('location_accuracy_m', models.PositiveIntegerField(blank=True, help_text='Raio de confiança em metros. Vazio significa localização não verificada.', null=True, verbose_name='precisão da localização (m)')),
                ('location_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='localização verificada em')),
                ('map_reference', models.CharField(blank=True, max_length=40, verbose_name='referência do pin')),
                ('area_m2', models.PositiveIntegerField(blank=True, null=True, verbose_name='área construída (m²)')),
                ('land_area_m2', models.PositiveIntegerField(blank=True, null=True, verbose_name='área do terreno (m²)')),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='quartos')),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='casas de banho')),
                ('has_water_tank', models.BooleanField(default=False, verbose_name='tem tanque de água')),
                ('has_generator', models.BooleanField(default=False, verbose_name='tem gerador')),
                ('is_furnished', models.BooleanField(default=False, verbose_name='mobilado')),
                ('has_garden', models.BooleanField(default=False, verbose_name='tem quintal')),
                ('has_pool', models.BooleanField(default=False, verbose_name='tem piscina')),
                ('has_parking', models.BooleanField(default=False, verbose_name='tem parque de estacionamento')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado em')),
                ('curated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties_curated', to=settings.AUTH_USER_MODEL, verbose_name='curador responsável')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.ownerprofile', verbose_name='proprietário')),
            ],
            options={
                'verbose_name': 'imóvel',
                'verbose_name_plural': 'imóveis',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('WEB_FORM', 'Formulário de adesão'), ('PHONE_CALL', 'Chamada'), ('IN_PERSON', 'Presencial')], max_length=12, verbose_name='canal de entrada')),
                ('owner_name_declared', models.CharField(max_length=150, verbose_name='nome declarado')),
                ('owner_phone_declared', models.CharField(max_length=20, validators=[apps.core.validators.validate_angolan_phone], verbose_name='telefone declarado')),
                ('photos_confirmed', models.BooleanField(default=False, verbose_name='fotos confirmadas')),
                ('location_confirmed', models.BooleanField(default=False, verbose_name='localização confirmada por satélite')),
                ('price_confirmed', models.BooleanField(default=False, verbose_name='preço confirmado')),
                ('legal_documents_confirmed', models.BooleanField(default=False, verbose_name='documentação legal recolhida')),
                ('owner_id_confirmed', models.BooleanField(default=False, verbose_name='identidade do proprietário confirmada')),
                ('notes', models.TextField(blank=True, verbose_name='notas da triagem')),
                ('triaged_at', models.DateTimeField(blank=True, null=True, verbose_name='triado em')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='properties.property', verbose_name='imóvel')),
                ('triaged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions_triaged', to=settings.AUTH_USER_MODEL, verbose_name='triado por')),
            ],
            options={
                'verbose_name': 'captação de imóvel',
                'verbose_name_plural': 'captações de imóveis',
            },
        ),
        migrations.CreateModel(
            name='PropertyStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20, verbose_name='estado anterior')),
                ('to_status', models.CharField(max_length=20, verbose_name='novo estado')),
                ('reason', models.CharField(blank=True, max_length=240, verbose_name='justificação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registado em')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_status_events', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='properties.property', verbose_name='imóvel')),
            ],
            options={
                'verbose_name': 'evento de estado',
                'verbose_name_plural': 'eventos de estado',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/%Y/%m/', verbose_name='fotografia')),
                ('caption', models.CharField(blank=True, max_length=140, verbose_name='legenda')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='imóvel')),
            ],
            options={
                'verbose_name': 'fotografia',
                'verbose_name_plural': 'fotografias',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('OWNERSHIP_TITLE', 'Escritura'), ('LAND_REGISTRY', 'Certidão de registo predial'), ('IUR', 'Imposto único de renda'), ('LEASE_CONTRACT', 'Contrato de arrendamento'), ('ID_DOCUMENT', 'Documento de identificação do proprietário'), ('URBAN_CERTIFICATE', 'Certidão de conformidade urbanística')], max_length=20, verbose_name='tipo de documento')),
                ('file', models.FileField(blank=True, upload_to='documents/%Y/%m/', verbose_name='ficheiro')),
                ('status', models.CharField(choices=[('PENDING', 'Por verificar'), ('VERIFIED', 'Verificado'), ('REJECTED', 'Recusado')], db_index=True, default='PENDING', max_length=10, verbose_name='verificação')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verificado em')),
                ('rejection_reason', models.CharField(blank=True, max_length=240, verbose_name='motivo da recusa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property', verbose_name='imóvel')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents_verified', to=settings.AUTH_USER_MODEL, verbose_name='verificado por')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
            },
        ),
        migrations.AddConstraint(
            model_name='propertydocument',
            constraint=models.UniqueConstraint(fields=('property', 'document_type'), name='unique_document_per_property'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'purpose'], name='prop_status_purpose_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'province_ref'], name='prop_status_province_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['type', 'status'], name='prop_type_status_idx'),
        ),
    ]
