# Generated by Django 4.2 on 2026-09-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['latitude', 'longitude'], name='prop_lat_lon_idx'),
        ),
    ]
