# Generated by Django 4.2 on 2026-09-26 19:24

import apps.core.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0004_quando_cubango_vira_quando'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydocument',
            name='file',
            field=models.FileField(blank=True, storage=apps.core.storage.storage_documentacao, upload_to='documents/%Y/%m/', verbose_name='ficheiro'),
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço de origem')),
                ('user_agent', models.CharField(blank=True, max_length=200, verbose_name='navegador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='aberto em')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_access_logs', to=settings.AUTH_USER_MODEL, verbose_name='aberto por')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='properties.propertydocument', verbose_name='documento')),
            ],
            options={
                'verbose_name': 'acesso a documento',
                'verbose_name_plural': 'acessos a documentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
