# Generated by Django 4.2 on 2026-09-26 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_propertydocument_file_documentaccesslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentaccesslog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_logs', to='properties.propertydocument', verbose_name='documento'),
        ),
    ]
