# Generated by Django 4.2 on 2026-09-27 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0006_alter_documentaccesslog_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentaccesslog',
            name='document_type',
            field=models.CharField(blank=True, max_length=32, verbose_name='tipo de documento'),
        ),
        migrations.AddField(
            model_name='documentaccesslog',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ficheiro'),
        ),
        migrations.AddField(
            model_name='documentaccesslog',
            name='property_reference',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='referência do imóvel'),
        ),
        migrations.AlterField(
            model_name='documentaccesslog',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='properties.propertydocument', verbose_name='documento'),
        ),
        migrations.CreateModel(
            name='PropertyDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=32, verbose_name='referência')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('status_at_deletion', models.CharField(max_length=24, verbose_name='estado')),
                ('reason', models.TextField(verbose_name='motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='apagado em')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_deletions', to=settings.AUTH_USER_MODEL, verbose_name='apagado por')),
            ],
            options={
                'verbose_name': 'imóvel apagado',
                'verbose_name_plural': 'imóveis apagados',
                'ordering': ['-created_at'],
            },
        ),
    ]
