# Generated by Django 4.2.30 on 2026-09-28 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_preenche_o_retrato_dos_acessos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-published_at', '-created_at', '-id'], 'verbose_name': 'imóvel', 'verbose_name_plural': 'imóveis'},
        ),
        migrations.AlterModelOptions(
            name='propertystatusevent',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'evento de estado', 'verbose_name_plural': 'eventos de estado'},
        ),
    ]
