# Generated by Django 4.2.30 on 2026-09-28 19:45

"""Desempata o registo de acessos, os proprietários e os apagamentos pelo `id`.

O `DocumentAccessLog` é a prova de quem leu um documento, e é consultada para
investigar: dois acessos no mesmo instante desempates no servidor de base de
dados, e o mesmo acesso aparece em duas páginas. `PropertyDeletion` tem o mesmo
formato, e `OwnerProfile` empata no `full_name` como a lista de contas.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_desempata_a_ordem_do_historico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentaccesslog',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'acesso a documento', 'verbose_name_plural': 'acessos a documentos'},
        ),
        migrations.AlterModelOptions(
            name='ownerprofile',
            options={'ordering': ['full_name', 'id'], 'verbose_name': 'proprietário', 'verbose_name_plural': 'proprietários'},
        ),
        migrations.AlterModelOptions(
            name='propertydeletion',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'imóvel apagado', 'verbose_name_plural': 'imóveis apagados'},
        ),
    ]
