# Generated by Django 4.2 on 2026-09-25 21:48

import apps.core.validators
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('ESCALATED', 'Escalado para a equipa'), ('RESOLVED', 'Resolvido')], db_index=True, default='OPEN', max_length=12, verbose_name='estado')),
                ('handled_by', models.CharField(choices=[('AI', 'Assistente'), ('HUMAN', 'Equipa')], default='AI', max_length=6, verbose_name='tratado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada em')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversations_assigned', to=settings.AUTH_USER_MODEL, verbose_name='agente responsável')),
            ],
            options={
                'verbose_name': 'conversa',
                'verbose_name_plural': 'conversas',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='nome')),
                ('phone', models.CharField(max_length=20, validators=[apps.core.validators.validate_angolan_phone], verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('lead_type', models.CharField(choices=[('OWNER_INTAKE', 'Captação de proprietário'), ('CLIENT_ENQUIRY', 'Consulta de cliente')], db_index=True, max_length=16, verbose_name='tipo')),
                ('status', models.CharField(choices=[('NEW', 'Novo'), ('CONTACTED', 'Contactado'), ('QUALIFIED', 'Qualificado'), ('CONVERTED', 'Convertido'), ('DISQUALIFIED', 'Descartado')], db_index=True, default='NEW', max_length=14, verbose_name='estado')),
                ('purpose_interest', models.CharField(blank=True, choices=[('', 'Não indicado'), ('RENT', 'Arrendar'), ('SALE', 'Vender'), ('LAND', 'Terreno')], max_length=20, verbose_name='interesse')),
                ('message', models.TextField(blank=True, verbose_name='mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado em')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads_assigned', to=settings.AUTH_USER_MODEL, verbose_name='atribuído a')),
                ('property_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='properties.property', verbose_name='imóvel de interesse')),
            ],
            options={
                'verbose_name': 'contacto',
                'verbose_name_plural': 'contactos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField(verbose_name='marcada para')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=45, verbose_name='duração (minutos)')),
                ('status', models.CharField(choices=[('PENDING', 'Por confirmar'), ('CONFIRMED', 'Confirmada'), ('DECLINED', 'Recusada'), ('COMPLETED', 'Realizada')], db_index=True, default='PENDING', max_length=10, verbose_name='estado')),
                ('notes', models.CharField(blank=True, max_length=240, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits_handled', to=settings.AUTH_USER_MODEL, verbose_name='tratada por')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='concierge.lead', verbose_name='contacto associado')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to='properties.property', verbose_name='imóvel')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits_requested', to=settings.AUTH_USER_MODEL, verbose_name='pedido por')),
            ],
            options={
                'verbose_name': 'pedido de visita',
                'verbose_name_plural': 'pedidos de visita',
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor proposto')),
                ('currency', models.CharField(default='AOA', max_length=3, verbose_name='moeda')),
                ('message', models.TextField(blank=True, verbose_name='justificação da proposta')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submetida'), ('UNDER_REVIEW', 'Em análise'), ('ACCEPTED', 'Aceite'), ('REJECTED', 'Recusada'), ('WITHDRAWN', 'Retirada')], db_index=True, default='SUBMITTED', max_length=12, verbose_name='estado')),
                ('response_notes', models.TextField(blank=True, verbose_name='resposta da equipa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='respondida em')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='properties.property', verbose_name='imóvel')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers_answered', to=settings.AUTH_USER_MODEL, verbose_name='respondida por')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers_submitted', to=settings.AUTH_USER_MODEL, verbose_name='submetida por')),
            ],
            options={
                'verbose_name': 'proposta',
                'verbose_name_plural': 'propostas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(choices=[('CLIENT', 'Cliente'), ('ASSISTANT', 'Assistente'), ('STAFF', 'Equipa')], max_length=10, verbose_name='autor')),
                ('body', models.TextField(verbose_name='conteúdo')),
                ('is_escalation_notice', models.BooleanField(default=False, verbose_name='aviso de escalação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='enviada em')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='concierge.conversation', verbose_name='conversa')),
            ],
            options={
                'verbose_name': 'mensagem',
                'verbose_name_plural': 'mensagens',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='concierge.lead', verbose_name='contacto'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='property_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='properties.property', verbose_name='imóvel em discussão'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='cliente'),
        ),
        migrations.AddIndex(
            model_name='visitrequest',
            index=models.Index(fields=['property', 'status'], name='visit_property_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_type', 'status'], name='lead_type_status_idx'),
        ),
    ]
