# Generated by Django 4.2 on 2026-09-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='uso interno da equipa'),
        ),
    ]
