# Generated by Django 4.2.30 on 2026-09-28 19:45

"""Desempata as quatro listas de `concierge` pelo `id`.

Nenhuma delas mudava de conteúdo: só se acrescenta a chave que faltava no fim
da ordenação. A fila de contactos é paginada, e `created_at` é `auto_now_add` no
MySQL — dois contactos registados no mesmo instante ficam com a mesma data e a
ordem passa a ser do servidor de base de dados, que é a mesma linha em duas
páginas.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0003_marca_internas_as_razoes_tecnicas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at', '-id'], 'verbose_name': 'conversa', 'verbose_name_plural': 'conversas'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'contacto', 'verbose_name_plural': 'contactos'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'proposta', 'verbose_name_plural': 'propostas'},
        ),
        migrations.AlterModelOptions(
            name='visitrequest',
            options={'ordering': ['-scheduled_for', '-id'], 'verbose_name': 'pedido de visita', 'verbose_name_plural': 'pedidos de visita'},
        ),
    ]
