# Generated by Django 4.2.30 on 2026-09-28 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('concierge', '0004_alter_conversation_options_alter_lead_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counters', to='concierge.offer', verbose_name='contraproposta a'),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='decline_reason',
            field=models.CharField(blank=True, max_length=240, verbose_name='motivo da recusa'),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='handled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='tratada em'),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='reconfirmation_flagged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='pedido de reconfirmação em'),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='reminded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='lembrete enviado em'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submetida'), ('UNDER_REVIEW', 'Em análise'), ('COUNTERED', 'Contraproposta'), ('ACCEPTED', 'Aceite'), ('REJECTED', 'Recusada'), ('WITHDRAWN', 'Retirada')], db_index=True, default='SUBMITTED', max_length=12, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers_submitted', to=settings.AUTH_USER_MODEL, verbose_name='criada por'),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Por confirmar'), ('CONFIRMED', 'Confirmada'), ('DECLINED', 'Recusada'), ('COMPLETED', 'Realizada'), ('NO_SHOW', 'Não compareceu')], db_index=True, default='PENDING', max_length=10, verbose_name='estado'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['property', 'status'], name='offer_property_status_idx'),
        ),
    ]
